Repository hackforla/VRMS, pull requests merged in 2025-06, with the labels that each got.

#1840 Updated HTML to MUI components for Home comp
  client/src/pages/Home.jsx
  client/src/sass/Home.scss
Labels: complexity: small, ready for 2nd review

#1727 Migrated edit users to Material UI
  client/src/components/user-admin/EditUsers.jsx
Labels: ready for dev lead, complexity: small

#1744 Update newuser to mui
  client/src/pages/NewUser.jsx
Labels: complexity: small
