Repository hackforla/VRMS, pull requests merged in 2025-05, with the labels that each got.

#1875 Updated HTML to MUI components in ReturnUserForm
  client/src/components/presentational/returnUserForm.jsx
  client/src/pages/CheckInForm.jsx
  client/src/sass/CheckIn.scss
Labels: merge before rebuild

#1805 Event Name Validation: blacklisted strings
  client/src/components/manageProjects/utilities/validateEventForm.js
  client/src/utils/blacklist.js
  client/src/utils/stringUtils.js
Labels: ready for dev lead

#1764 migrate returninguser to mui
  client/src/pages/ReturningUser.jsx
Labels: complexity: small, ready for 2nd review

#1812 add form validation for zoom google meet
  client/src/components/manageProjects/createNewEvent.jsx
  client/src/components/manageProjects/eventForm.jsx
  client/src/components/manageProjects/utilities/validateEventForm.js
Labels: complexity: small, ready for 2nd review

#1869 Convert Events.js to MUI Components
  client/src/pages/Events.jsx
  client/src/sass/Events.scss
Labels: ready for dev lead, ready for 2nd review
