Repository hackforla/VRMS, pull requests merged in 2025-02, with the labels that each got.

#1848 Changed Auth.js to MUI
  client/src/components/auth/Auth.jsx
Labels: complexity: small

#1844 EventForm Refactor to Material UI
  client/src/components/manageProjects/editableMeeting.jsx
  client/src/components/manageProjects/eventForm.jsx
  client/src/sass/CheckIn.scss
  client/src/sass/ManageProjects.scss
Labels: ready for dev lead, complexity: small

#1851 1839 date fix
  backend/package.json
  backend/workers/createRecurringEvents.js
  backend/workers/createRecurringEvents.test.js
  backend/yarn.lock
Labels: complexity: medium

#1850 Update HTML components to MUI components for ManageProjects page
  client/src/pages/ManageProjects.jsx
Labels: ready for dev lead, complexity: small, ready for 2nd review

#1866 MUI updates to CheckInForm.jsx
  client/src/pages/CheckInForm.jsx
Labels: ready for dev lead, ready for 2nd review
