Repository hackforla/VRMS, pull requests merged in 2025-03, with the labels that each got.

#1864 Importing fonts
  client/src/fonts/SourceCodePro-Bold.otf
  client/src/fonts/SourceCodePro-Medium.otf
  client/src/fonts/SourceCodePro-Semibold.otf
  client/src/fonts/open-sans/LICENSE.txt
  client/src/fonts/open-sans/opensans-bold.ttf
  client/src/fonts/open-sans/opensans-bold.woff
  client/src/fonts/open-sans/opensans-bold.woff2
  client/src/fonts/open-sans/opensans-regular.ttf
  client/src/fonts/open-sans/opensans-regular.woff
  client/src/fonts/open-sans/opensans-regular.woff2
  client/src/fonts/open-sans/opensans-semibold.ttf
  client/src/fonts/open-sans/opensans-semibold.woff
  client/src/fonts/open-sans/opensans-semibold.woff2
  client/src/index.scss
  client/src/sass/ProjectLeaderDashboard.module.scss
Labels: complexity: small, ready for 2nd review

#1725 Migrated Checkin Button to Material UI
  client/src/components/presentational/CheckInButtons.jsx
Labels: complexity: small

#1796 Google Drive Form Validation
  client/src/components/data.js
  client/src/components/parts/form/ValidatedTextField.jsx
Labels: complexity: small, ready for 2nd review

#1849 Replace html elements with MUI in editableField.jsx
  client/src/components/manageProjects/editableField.jsx
Labels: ready for dev lead, complexity: small, ready for 2nd review

#1852 Fixes #1472 - Create withAuth component to manage automatic redirect to login page
  client/src/App.jsx
  client/src/components/ProjectForm.jsx
  client/src/components/admin/dashboard/index.jsx
  client/src/components/manageProjects/addProject.jsx
  client/src/hooks/withAuth.jsx
  client/src/pages/Events.jsx
  client/src/pages/ManageProjects.jsx
  client/src/pages/ProjectList.jsx
  client/src/pages/UserAdmin.jsx
Labels: complexity: medium, ready for 2nd review

#1743 update to mui footer
  client/src/components/Footer.jsx
Labels: complexity: small, ready for 2nd review
